name: Latest blog post workflow
on:
  schedule:
    - cron: '0 0 * * *' # 매일 자정(UTC)에 실행
  workflow_dispatch: # 수동 실행도 가능

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://alswp006.github.io/feed.xml"
          max_post_count: 5
          template: "$newline- [$title]($url) - $date"
          date_format: "yyyy.MM.dd"
